import type { TUser } from './data-types';

export const USERS_DATA: TUser[] = [
  {
    gender: 'male',
    userId: 'user-1',
    name: 'Александр',
    city: 'Москва',
    age: 32,
    mail: 'alexander@example.com',
    password: 'password1',
    description: 'Опытный менеджер, ищу возможности для профессионального роста',
    incoming: [],
    outgoing: [],
    image: '/user-1.jpg',
    likes: ['user-5', 'user-12'],
  },
  {
    gender: 'female',
    userId: 'user-2',
    name: 'Екатерина',
    city: 'Санкт-Петербург',
    age: 28,
    mail: 'ekaterina@example.com',
    password: 'password2',
    description: 'Дизайнер с опытом, хочу расширить свои навыки',
    incoming: [],
    outgoing: [],
    image: '/user-2.jpg',
    likes: ['user-8', 'user-15'],
  },
  {
    gender: 'male',
    userId: 'user-3',
    name: 'Михаил',
    city: 'Новосибирск',
    age: 35,
    mail: 'mikhail@example.com',
    password: 'password3',
    description: 'Преподаватель языка, увлекаюсь психологией',
    incoming: [],
    outgoing: [],
    image: '/user-3.jpg',
    likes: ['user-10'],
  },
  // Продолжение списка...
  {
    gender: 'female',
    userId: 'user-4',
    name: 'Ольга',
    city: 'Екатеринбург',
    age: 29,
    mail: 'olga@example.com',
    password: 'password4',
    description: 'Финансист, веду здоровый образ жизни',
    incoming: [],
    outgoing: [],
    image: '/user-4.jpg',
    likes: ['user-7', 'user-18'],
  },
  {
    gender: 'male',
    userId: 'user-5',
    name: 'Дмитрий',
    city: 'Казань',
    age: 31,
    mail: 'dmitry@example.com',
    password: 'password5',
    description: 'Разработчик, изучаю новые технологии и языки',
    incoming: [],
    outgoing: [],
    image: '/user-5.jpg',
    likes: ['user-3', 'user-9', 'user-20'],
  },
  {
    gender: 'female',
    userId: 'user-6',
    name: 'Анна',
    city: 'Нижний Новгород',
    age: 27,
    mail: 'anna@example.com',
    password: 'password6',
    description: 'Профессиональный тренер, увлекаюсь здоровым образом жизни',
    incoming: [],
    outgoing: [],
    image: '/user-6.jpg',
    likes: ['user-11', 'user-14'],
  },
  {
    gender: 'male',
    userId: 'user-7',
    name: 'Сергей',
    city: 'Челябинск',
    age: 33,
    mail: 'sergey@example.com',
    password: 'password7',
    description: 'Шеф-повар, изучаю кухни разных стран',
    incoming: [],
    outgoing: [],
    image: '/user-7.jpg',
    likes: ['user-2', 'user-19'],
  },
  {
    gender: 'female',
    userId: 'user-8',
    name: 'Мария',
    city: 'Самара',
    age: 26,
    mail: 'maria@example.com',
    password: 'password8',
    description: 'Видеограф, создаю креативный контент',
    incoming: [],
    outgoing: [],
    image: '/user-8.jpg',
    likes: ['user-4', 'user-16'],
  },
  {
    gender: 'male',
    userId: 'user-9',
    name: 'Артем',
    city: 'Омск',
    age: 30,
    mail: 'artem@example.com',
    password: 'password9',
    description: 'Лингвист, увлекаюсь восточной культурой',
    incoming: [],
    outgoing: [],
    image: '/user-9.jpg',
    likes: ['user-13'],
  },
  {
    gender: 'female',
    userId: 'user-10',
    name: 'Виктория',
    city: 'Ростов-на-Дону',
    age: 34,
    mail: 'victoria@example.com',
    password: 'password10',
    description: 'HR-специалист, развиваюсь в международном направлении',
    incoming: [],
    outgoing: [],
    image: '/user-10.jpg',
    likes: ['user-1', 'user-17'],
  },
  // Продолжение до 40 пользователей...
  {
    gender: 'male',
    userId: 'user-11',
    name: 'Андрей',
    city: 'Москва',
    age: 29,
    mail: 'andrey@example.com',
    password: 'password11',
    description: 'Фотограф, работаю в портретном жанре',
    incoming: [],
    outgoing: [],
    image: '/user-11.jpg',
    likes: ['user-6', 'user-22'],
  },
  {
    gender: 'female',
    userId: 'user-12',
    name: 'Елена',
    city: 'Санкт-Петербург',
    age: 31,
    mail: 'elena@example.com',
    password: 'password12',
    description: 'Маркетолог, развиваю личные бренды',
    incoming: [],
    outgoing: [],
    image: '/user-12.jpg',
    likes: ['user-3', 'user-25'],
  },
  {
    gender: 'male',
    userId: 'user-13',
    name: 'Кирилл',
    city: 'Новосибирск',
    age: 27,
    mail: 'kirill@example.com',
    password: 'password13',
    description: 'Преподаватель японского, увлекаюсь культурой',
    incoming: [],
    outgoing: [],
    image: '/user-13.jpg',
    likes: ['user-9', 'user-30'],
  },
  {
    gender: 'female',
    userId: 'user-14',
    name: 'Наталья',
    city: 'Екатеринбург',
    age: 36,
    mail: 'natalia@example.com',
    password: 'password14',
    description: 'Организатор пространства, помогаю наводить порядок',
    incoming: [],
    outgoing: [],
    image: '/user-14.jpg',
    likes: ['user-5', 'user-21'],
  },
  {
    gender: 'male',
    userId: 'user-15',
    name: 'Павел',
    city: 'Казань',
    age: 38,
    mail: 'pavel@example.com',
    password: 'password15',
    description: 'Менеджер по продажам, развиваю навыки презентации',
    incoming: [],
    outgoing: [],
    image: '/user-15.jpg',
    likes: ['user-12', 'user-24'],
  },
  {
    gender: 'female',
    userId: 'user-16',
    name: 'Алиса',
    city: 'Нижний Новгород',
    age: 25,
    mail: 'alisa@example.com',
    password: 'password16',
    description: 'Инструктор йоги, изучаю восточную медицину',
    incoming: [],
    outgoing: [],
    image: '/user-16.jpg',
    likes: ['user-8', 'user-17'],
  },
  {
    gender: 'male',
    userId: 'user-17',
    name: 'Иван',
    city: 'Челябинск',
    age: 40,
    mail: 'ivan@example.com',
    password: 'password17',
    description: 'Шеф-повар, специализируюсь на итальянских блюдах',
    incoming: [],
    outgoing: [],
    image: '/user-17.jpg',
    likes: ['user-10', 'user-16'],
  },
  {
    gender: 'female',
    userId: 'user-18',
    name: 'София',
    city: 'Самара',
    age: 23,
    mail: 'sofia@example.com',
    password: 'password18',
    description: 'Музыкант, создаю электронные треки',
    incoming: [],
    outgoing: [],
    image: '/user-18.jpg',
    likes: ['user-4', 'user-19'],
  },
  {
    gender: 'male',
    userId: 'user-19',
    name: 'Денис',
    city: 'Омск',
    age: 37,
    mail: 'denis@example.com',
    password: 'password19',
    description: 'Психолог, специализируюсь на когнитивных методиках',
    incoming: [],
    outgoing: [],
    image: '/user-19.jpg',
    likes: ['user-7', 'user-18'],
  },
  {
    gender: 'female',
    userId: 'user-20',
    name: 'Анастасия',
    city: 'Ростов-на-Дону',
    age: 28,
    mail: 'anastasia@example.com',
    password: 'password20',
    description: 'Преподаватель испанского, люблю латиноамериканскую культуру',
    incoming: [],
    outgoing: [],
    image: '/user-20.jpg',
    likes: ['user-5', 'user-15'],
  },
  // Остальные пользователи 21-40...
  {
    gender: 'male',
    userId: 'user-21',
    name: 'Георгий',
    city: 'Москва',
    age: 33,
    mail: 'georgy@example.com',
    password: 'password21',
    description: 'Синолог, изучаю традиционные китайские практики',
    incoming: [],
    outgoing: [],
    image: '/user-21.jpg',
    likes: ['user-14', 'user-23'],
  },
  {
    gender: 'female',
    userId: 'user-22',
    name: 'Валерия',
    city: 'Санкт-Петербург',
    age: 26,
    mail: 'valeria@example.com',
    password: 'password22',
    description: 'Иллюстратор, работаю в цифровом формате',
    incoming: [],
    outgoing: [],
    image: '/user-22.jpg',
    likes: ['user-11', 'user-27'],
  },
  {
    gender: 'male',
    userId: 'user-23',
    name: 'Артур',
    city: 'Новосибирск',
    age: 30,
    mail: 'arthur@example.com',
    password: 'password23',
    description: 'Преподаватель французского, увлекаюсь литературой',
    incoming: [],
    outgoing: [],
    image: '/user-23.jpg',
    likes: ['user-21'],
  },
  {
    gender: 'female',
    userId: 'user-24',
    name: 'Юлия',
    city: 'Екатеринбург',
    age: 35,
    mail: 'yulia@example.com',
    password: 'password24',
    description: 'Психолог, помогаю улучшить коммуникативные навыки',
    incoming: [],
    outgoing: [],
    image: '/user-24.jpg',
    likes: ['user-15', 'user-28'],
  },
  {
    gender: 'male',
    userId: 'user-25',
    name: 'Роман',
    city: 'Казань',
    age: 29,
    mail: 'roman@example.com',
    password: 'password25',
    description: 'Аналитик данных, развиваюсь в области AI',
    incoming: [],
    outgoing: [],
    image: '/user-25.jpg',
    likes: ['user-12', 'user-30'],
  },
  {
    gender: 'female',
    userId: 'user-26',
    name: 'Евгения',
    city: 'Нижний Новгород',
    age: 31,
    mail: 'evgenia@example.com',
    password: 'password26',
    description: 'Нутрициолог, помогаю сбалансировать рацион',
    incoming: [],
    outgoing: [],
    image: '/user-26.jpg',
    likes: ['user-17', 'user-29'],
  },
  {
    gender: 'male',
    userId: 'user-27',
    name: 'Максим',
    city: 'Челябинск',
    age: 24,
    mail: 'maxim@example.com',
    password: 'password27',
    description: 'Видеоблогер, создаю образовательный контент',
    incoming: [],
    outgoing: [],
    image: '/user-27.jpg',
    likes: ['user-22', 'user-18'],
  },
  {
    gender: 'female',
    userId: 'user-28',
    name: 'Арина',
    city: 'Самара',
    age: 27,
    mail: 'arina@example.com',
    password: 'password28',
    description: 'Преподаватель английского для технических специалистов',
    incoming: [],
    outgoing: [],
    image: '/user-28.jpg',
    likes: ['user-24', 'user-5'],
  },
  {
    gender: 'female',
    userId: 'user-29',
    name: 'Вероника',
    city: 'Омск',
    age: 32,
    mail: 'veronika@example.com',
    password: 'password29',
    description: 'Арт-терапевт, работаю с детьми и взрослыми',
    incoming: [],
    outgoing: [],
    image: '/user-29.jpg',
    likes: ['user-19', 'user-26'],
  },
  {
    gender: 'male',
    userId: 'user-30',
    name: 'Константин',
    city: 'Ростов-на-Дону',
    age: 39,
    mail: 'konstantin@example.com',
    password: 'password30',
    description: 'Финансовый консультант, помогаю с инвестициями',
    incoming: [],
    outgoing: [],
    image: '/user-30.jpg',
    likes: ['user-13', 'user-25'],
  },
  // Пользователи 31-40...
  {
    gender: 'female',
    userId: 'user-31',
    name: 'Татьяна',
    city: 'Москва',
    age: 28,
    mail: 'tatiana@example.com',
    password: 'password31',
    description: 'Тренер по развитию памяти и скорочтению',
    incoming: [],
    outgoing: [],
    image: '/user-31.jpg',
    likes: ['user-21', 'user-33'],
  },
  {
    gender: 'male',
    userId: 'user-32',
    name: 'Игорь',
    city: 'Санкт-Петербург',
    age: 34,
    mail: 'igor@example.com',
    password: 'password32',
    description: 'Специалист по визуальным коммуникациям',
    incoming: [],
    outgoing: [],
    image: '/user-32.jpg',
    likes: ['user-12', 'user-22'],
  },
  {
    gender: 'female',
    userId: 'user-33',
    name: 'Людмила',
    city: 'Новосибирск',
    age: 41,
    mail: 'lyudmila@example.com',
    password: 'password33',
    description: 'Преподаватель немецкого с историческим образованием',
    incoming: [],
    outgoing: [],
    image: '/user-33.jpg',
    likes: ['user-31', 'user-35'],
  },
  {
    gender: 'male',
    userId: 'user-34',
    name: 'Вадим',
    city: 'Екатеринбург',
    age: 30,
    mail: 'vadim@example.com',
    password: 'password34',
    description: 'Художник, преподаю основы академического рисунка',
    incoming: [],
    outgoing: [],
    image: '/user-34.jpg',
    likes: ['user-24', 'user-36'],
  },
  {
    gender: 'female',
    userId: 'user-35',
    name: 'Ангелина',
    city: 'Казань',
    age: 29,
    mail: 'angelina@example.com',
    password: 'password35',
    description: 'Коуч по продуктивности и управлению временем',
    incoming: [],
    outgoing: [],
    image: '/user-35.jpg',
    likes: ['user-33', 'user-38'],
  },
  {
    gender: 'male',
    userId: 'user-36',
    name: 'Станислав',
    city: 'Нижний Новгород',
    age: 32,
    mail: 'stanislav@example.com',
    password: 'password36',
    description: 'Фитнес-тренер, специализируюсь на функциональных тренировках',
    incoming: [],
    outgoing: [],
    image: '/user-36.jpg',
    likes: ['user-34', 'user-40'],
  },
  {
    gender: 'female',
    userId: 'user-37',
    name: 'Александра',
    city: 'Челябинск',
    age: 26,
    mail: 'alexandra@example.com',
    password: 'password37',
    description: 'Саунд-дизайнер, работаю с электронной музыкой',
    incoming: [],
    outgoing: [],
    image: '/user-37.jpg',
    likes: ['user-27', 'user-39'],
  },
  {
    gender: 'male',
    userId: 'user-38',
    name: 'Борис',
    city: 'Самара',
    age: 45,
    mail: 'boris@example.com',
    password: 'password38',
    description: 'Астролог, изучаю взаимосвязь звезд и характера',
    incoming: [],
    outgoing: [],
    image: '/user-38.jpg',
    likes: ['user-35'],
  },
  {
    gender: 'female',
    userId: 'user-39',
    name: 'Элина',
    city: 'Омск',
    age: 31,
    mail: 'elina@example.com',
    password: 'password39',
    description: 'Кондитер, специализируюсь на французских десертах',
    incoming: [],
    outgoing: [],
    image: '/user-39.jpg',
    likes: ['user-37', 'user-20'],
  },
  {
    gender: 'male',
    userId: 'user-40',
    name: 'Глеб',
    city: 'Ростов-на-Дону',
    age: 36,
    mail: 'gleb@example.com',
    password: 'password40',
    description: 'Предприниматель, делюсь опытом ведения бизнеса',
    incoming: [],
    outgoing: [],
    image: '/user-40.jpg',
    likes: ['user-36', 'user-25'],
  },
];
