import type { TCard } from './data-types';

export const CARDS_DATA: TCard[] = [
  {
    id: 'card-1',
    userId: 'user-1',
    teachSkill: [{ title: 'Управление проектами', type: 'business', subType: 'team-management' }],
    learnSkill: [
      { title: 'Основы маркетинга', type: 'business', subType: 'marketing' },
      { title: 'Деловой английский', type: 'languages', subType: 'english' },
    ],
    name: 'Александр',
    city: 'Москва',
    age: 32,
    description: 'Опытный менеджер, ищу возможности для профессионального роста',
    fullDescription:
      'Я научу вас эффективно управлять проектами любой сложности. Расскажу о методах Agile и Waterfall, помогу освоить инструменты планирования. Поделюсь секретами управления командой и распределения задач. Научу оценивать риски и минимизировать потери времени. Вы сможете уверенно вести проекты от идеи до реализации.',
    gender: 'male',
    createdAt: 1672531200000,
    likes: ['user-5', 'user-12'],
    src: 'https://s0.rbk.ru/v6_top_pics/media/img/6/57/756781333421576.webp',
  },
  {
    id: 'card-2',
    userId: 'user-2',
    teachSkill: [{ title: 'Графический дизайн', type: 'art', subType: 'drawing' }],
    learnSkill: [
      { title: 'Фотография для начинающих', type: 'art', subType: 'photo' },
      { title: 'Основы композиции', type: 'art', subType: 'drawing' },
    ],
    name: 'Екатерина',
    city: 'Санкт-Петербург',
    age: 28,
    description: 'Дизайнер с опытом, хочу расширить свои навыки',
    fullDescription:
      'Научу вас создавать профессиональные дизайн-макеты в Figma и Adobe Photoshop. Расскажу о принципах цветовой гармонии и типографики. Покажу, как работать с брифом и ожиданиями заказчика. Научу создавать логотипы и фирменный стиль. Поделюсь лайфхаками для быстрого роста в профессии.',
    gender: 'female',
    createdAt: 1672617600000,
    likes: ['user-8', 'user-15'],
    src: '/user-2.jpg',
  },
  {
    id: 'card-3',
    userId: 'user-3',
    teachSkill: [{ title: 'Разговорный английский', type: 'languages', subType: 'english' }],
    learnSkill: [
      { title: 'Деловой французский', type: 'languages', subType: 'french' },
      { title: 'Основы психологии', type: 'education', subType: 'personal-development' },
    ],
    name: 'Михаил',
    city: 'Новосибирск',
    age: 35,
    description: 'Преподаватель языка, увлекаюсь психологией',
    fullDescription:
      'Помогу вам преодолеть языковой барьер и заговорить на английском свободно. Научу понимать нюансы произношения и использовать идиомы. Расскажу, как быстро расширить словарный запас. Поделюсь методиками запоминания сложных грамматических правил. Смоделируем реальные ситуации общения для практики.',
    gender: 'male',
    createdAt: 1672704000000,
    likes: ['user-10'],
    src: '/user-3.jpg',
  },
  {
    id: 'card-4',
    userId: 'user-4',
    teachSkill: [{ title: 'Финансовое планирование', type: 'home', subType: 'home-finances' }],
    learnSkill: [
      { title: 'Приготовление здоровой пищи', type: 'home', subType: 'cooking' },
      { title: 'Основы йоги', type: 'lifestyle', subType: 'yoga' },
    ],
    name: 'Ольга',
    city: 'Екатеринбург',
    age: 29,
    description: 'Финансист, веду здоровый образ жизни',
    fullDescription:
      'Научу вас грамотно распределять бюджет и достигать финансовых целей. Расскажу о методах учёта доходов и расходов. Покажу, как создать "финансовую подушку безопасности". Научу инвестировать с минимальными рисками. Поделюсь инструментами для долгосрочного финансового планирования.',
    gender: 'female',
    createdAt: 1672790400000,
    likes: ['user-7', 'user-18'],
    src: '/user-4.jpg',
  },
  {
    id: 'card-5',
    userId: 'user-5',
    teachSkill: [{ title: 'Основы программирования', type: 'education', subType: 'training' }],
    learnSkill: [
      { title: 'Китайский язык для начинающих', type: 'languages', subType: 'chinese' },
      { title: 'Управление временем', type: 'education', subType: 'personal-development' },
    ],
    name: 'Дмитрий',
    city: 'Казань',
    age: 31,
    description: 'Разработчик, изучаю новые технологии и языки',
    fullDescription:
      'Помогу сделать первые шаги в программировании на Python и JavaScript. Объясню основы алгоритмов и структур данных. Научу писать чистый и поддерживаемый код. Покажу, как решать типовые задачи на популярных платформах. Подготовлю к первому собеседованию в IT-компании.',
    gender: 'male',
    createdAt: 1672876800000,
    likes: ['user-3', 'user-9', 'user-20'],
    src: '/user-5.jpg',
  },
  {
    id: 'card-6',
    userId: 'user-6',
    teachSkill: [{ title: 'Фитнес-тренировки', type: 'lifestyle', subType: 'nutrition' }],
    learnSkill: [
      { title: 'Медитация для начинающих', type: 'lifestyle', subType: 'mindfulness' },
      { title: 'Основы здорового питания', type: 'lifestyle', subType: 'nutrition' },
    ],
    name: 'Анна',
    city: 'Нижний Новгород',
    age: 27,
    description: 'Профессиональный тренер, увлекаюсь здоровым образом жизни',
    fullDescription:
      'Научу правильно выполнять упражнения без риска травм. Составлю индивидуальную программу тренировок под ваши цели. Расскажу о работе разных групп мышц и их развитии. Покажу техники дыхания для повышения эффективности занятий. Помогу выработать привычку к регулярным тренировкам.',
    gender: 'female',
    createdAt: 1672963200000,
    likes: ['user-11', 'user-14'],
    src: '/user-6.jpg',
  },
  {
    id: 'card-7',
    userId: 'user-7',
    teachSkill: [{ title: 'Французская кухня', type: 'home', subType: 'cooking' }],
    learnSkill: [
      { title: 'Итальянский язык', type: 'languages', subType: 'other' },
      { title: 'Фуд-фотография', type: 'art', subType: 'photo' },
    ],
    name: 'Сергей',
    city: 'Челябинск',
    age: 33,
    description: 'Шеф-повар, изучаю кухни разных стран',
    fullDescription:
      'Научу готовить классические французские блюда с идеальной техникой. Расскажу секреты приготовления нежного суфле и воздушных круассанов. Покажу, как работать с тестом и соусами как профессиональный повар. Научу подбирать вина к блюдам. Поделюсь рецептами, проверенными в мишленовских ресторанах.',
    gender: 'male',
    createdAt: 1673049600000,
    likes: ['user-2', 'user-19'],
    src: '/user-7.jpg',
  },
  {
    id: 'card-8',
    userId: 'user-8',
    teachSkill: [{ title: 'Основы видеомонтажа', type: 'art', subType: 'mounting' }],
    learnSkill: [
      { title: 'Создание музыки', type: 'art', subType: 'music' },
      { title: 'Продвижение в соцсетях', type: 'business', subType: 'marketing' },
    ],
    name: 'Мария',
    city: 'Самара',
    age: 26,
    description: 'Видеограф, создаю креативный контент',
    fullDescription:
      'Научу монтировать видео в Adobe Premiere Pro на профессиональном уровне. Расскажу о принципах построения драматургии в роликах. Покажу, как работать с цветокоррекцией и звуком. Научу создавать плавные переходы и эффекты. Поделюсь лайфхаками для быстрого монтажа качественного контента.',
    gender: 'female',
    createdAt: 1673136000000,
    likes: ['user-4', 'user-16'],
    src: '/user-8.jpg',
  },
  {
    id: 'card-9',
    userId: 'user-9',
    teachSkill: [{ title: 'Немецкий язык', type: 'languages', subType: 'german' }],
    learnSkill: [
      { title: 'Японская каллиграфия', type: 'art', subType: 'drawing' },
      { title: 'Основы нейробиологии', type: 'education', subType: 'cognitive-skills' },
    ],
    name: 'Артем',
    city: 'Омск',
    age: 30,
    description: 'Лингвист, увлекаюсь восточной культурой',
    fullDescription:
      'Помогу освоить немецкий язык с нуля до уровня B1. Научу правильному произношению и построению предложений. Расскажу о культурных особенностях общения в Германии. Поделюсь методиками быстрого запоминания слов. Подготовлю к сдаче экзаменов Goethe-Institut.',
    gender: 'male',
    createdAt: 1673222400000,
    likes: ['user-13'],
    src: '/user-9.jpg',
  },
  {
    id: 'card-10',
    userId: 'user-10',
    teachSkill: [{ title: 'Управление персоналом', type: 'business', subType: 'team-management' }],
    learnSkill: [
      { title: 'Эффективные переговоры', type: 'business', subType: 'sales' },
      { title: 'Испанский язык', type: 'languages', subType: 'spanish' },
    ],
    name: 'Виктория',
    city: 'Ростов-на-Дону',
    age: 34,
    description: 'HR-специалист, развиваюсь в международном направлении',
    fullDescription:
      'Научу методам подбора и мотивации персонала. Расскажу, как проводить собеседования и оценивать кандидатов. Поделюсь техниками решения конфликтов в коллективе. Научу создавать систему KPI для сотрудников. Расскажу о современных тенденциях в управлении командой.',
    gender: 'female',
    createdAt: 1673308800000,
    likes: ['user-1', 'user-17'],
    src: '/user-10.jpg',
  },
  // 11-20
  {
    id: 'card-11',
    userId: 'user-11',
    teachSkill: [{ title: 'Фотопортрет', type: 'art', subType: 'photo' }],
    learnSkill: [
      { title: 'Обработка в Lightroom', type: 'art', subType: 'photo' },
      { title: 'Психология восприятия', type: 'education', subType: 'cognitive-skills' },
    ],
    name: 'Андрей',
    city: 'Москва',
    age: 29,
    description: 'Фотограф, работаю в портретном жанре',
    fullDescription:
      'Научу создавать профессиональные портреты с естественным светом. Расскажу секреты работы с моделью и выгодных ракурсов. Покажу как подчеркнуть индивидуальность человека в кадре. Научу базовой ретуши кожи без потери текстуры. Поделюсь техниками создания атмосферных портретов в разных локациях.',
    gender: 'male',
    createdAt: 1673395200000,
    likes: ['user-6', 'user-22'],
    src: '/user-11.jpg',
  },
  {
    id: 'card-12',
    userId: 'user-12',
    teachSkill: [{ title: 'Бренд-менеджмент', type: 'business', subType: 'brand' }],
    learnSkill: [
      { title: 'Копирайтинг', type: 'business', subType: 'marketing' },
      { title: 'Китайский язык', type: 'languages', subType: 'chinese' },
    ],
    name: 'Елена',
    city: 'Санкт-Петербург',
    age: 31,
    description: 'Маркетолог, развиваю личные бренды',
    fullDescription:
      'Научу создавать сильный личный бренд с нуля. Расскажу как позиционировать себя на рынке. Поделюсь техниками формирования уникального стиля. Научу упаковывать экспертность в соцсетях. Расскажу как монетизировать личный бренд без потери доверия аудитории.',
    gender: 'female',
    createdAt: 1673481600000,
    likes: ['user-3', 'user-25'],
    src: '/user-12.jpg',
  },
  {
    id: 'card-13',
    userId: 'user-13',
    teachSkill: [{ title: 'Японский язык', type: 'languages', subType: 'japanese' }],
    learnSkill: [
      { title: 'Каллиграфия', type: 'art', subType: 'drawing' },
      { title: 'Ментальная арифметика', type: 'education', subType: 'cognitive-skills' },
    ],
    name: 'Кирилл',
    city: 'Новосибирск',
    age: 27,
    description: 'Преподаватель японского, увлекаюсь культурой',
    fullDescription:
      'Научу основам японского языка с нуля. Расскажу особенности всех трех азбук (хирагана, катакана, кандзи). Поделюсь техниками запоминания иероглифов. Научу вести простые диалоги на бытовые темы. Расскажу о культурных особенностях общения в Японии.',
    gender: 'male',
    createdAt: 1673568000000,
    likes: ['user-9', 'user-30'],
    src: '/user-13.jpg',
  },
  {
    id: 'card-14',
    userId: 'user-14',
    teachSkill: [{ title: 'Организация пространства', type: 'home', subType: 'cleaning' }],
    learnSkill: [
      { title: 'Минимализм', type: 'lifestyle', subType: 'mindfulness' },
      { title: 'Фэн-шуй', type: 'home', subType: 'other' },
    ],
    name: 'Наталья',
    city: 'Екатеринбург',
    age: 36,
    description: 'Организатор пространства, помогаю наводить порядок',
    fullDescription:
      'Научу системам организации пространства в доме. Расскажу как избавиться от хлама без сожалений. Поделюсь техниками хранения вещей в малогабаритных квартирах. Научу создавать функциональные зоны в любом помещении. Расскажу как поддерживать порядок без ежедневных уборок.',
    gender: 'female',
    createdAt: 1673654400000,
    likes: ['user-5', 'user-21'],
    src: '/user-14.jpg',
  },
  {
    id: 'card-15',
    userId: 'user-15',
    teachSkill: [{ title: 'Продажи в B2B', type: 'business', subType: 'sales' }],
    learnSkill: [
      { title: 'Публичные выступления', type: 'business', subType: 'brand' },
      { title: 'Основы бухгалтерии', type: 'home', subType: 'home-finances' },
    ],
    name: 'Павел',
    city: 'Казань',
    age: 38,
    description: 'Менеджер по продажам, развиваю навыки презентации',
    fullDescription:
      'Научу стратегиям продаж в сегменте B2B. Расскажу как выстраивать долгосрочные отношения с клиентами. Поделюсь техниками ведения сложных переговоров. Научу составлять коммерческие предложения. Расскажу как увеличить средний чек и повторные продажи.',
    gender: 'male',
    createdAt: 1673740800000,
    likes: ['user-12', 'user-24'],
    src: '/user-15.jpg',
  },
  {
    id: 'card-16',
    userId: 'user-16',
    teachSkill: [{ title: 'Йога для начинающих', type: 'lifestyle', subType: 'yoga' }],
    learnSkill: [
      { title: 'Аюрведа', type: 'lifestyle', subType: 'nutrition' },
      { title: 'Основы анатомии', type: 'education', subType: 'training' },
    ],
    name: 'Алиса',
    city: 'Нижний Новгород',
    age: 25,
    description: 'Инструктор йоги, изучаю восточную медицину',
    fullDescription:
      'Научу базовым асанам и правильному дыханию. Расскажу как избежать травм при самостоятельных занятиях. Поделюсь техниками расслабления и медитации. Научу составлять индивидуальные комплексы упражнений. Расскажу о философии йоги и ее влиянии на качество жизни.',
    gender: 'female',
    createdAt: 1673827200000,
    likes: ['user-8', 'user-17'],
    src: '/user-16.jpg',
  },
  {
    id: 'card-17',
    userId: 'user-17',
    teachSkill: [{ title: 'Итальянская кухня', type: 'home', subType: 'cooking' }],
    learnSkill: [
      { title: 'Виноделие', type: 'lifestyle', subType: 'other' },
      { title: 'Фотография еды', type: 'art', subType: 'photo' },
    ],
    name: 'Иван',
    city: 'Челябинск',
    age: 40,
    description: 'Шеф-повар, специализируюсь на итальянских блюдах',
    fullDescription:
      'Научу готовить настоящую пасту и ризотто как в Италии. Расскажу секреты идеального соуса песто. Поделюсь техниками работы с тестом для пиццы. Научу выбирать правильные ингредиенты. Расскажу как сервировать блюда в итальянском стиле.',
    gender: 'male',
    createdAt: 1673913600000,
    likes: ['user-10', 'user-16'],
    src: '/user-17.jpg',
  },
  {
    id: 'card-18',
    userId: 'user-18',
    teachSkill: [{ title: 'Создание электронной музыки', type: 'art', subType: 'music' }],
    learnSkill: [
      { title: 'Звукорежиссура', type: 'art', subType: 'music' },
      { title: 'Продвижение артистов', type: 'business', subType: 'marketing' },
    ],
    name: 'София',
    city: 'Самара',
    age: 23,
    description: 'Музыкант, создаю электронные треки',
    fullDescription:
      'Научу основам работы в Ableton Live и FL Studio. Расскажу как создавать биты и мелодии. Поделюсь техниками сведения и мастеринга. Научу работать с MIDI-контроллерами. Расскажу как развивать музыкальный слух и чувство ритма.',
    gender: 'female',
    createdAt: 1674000000000,
    likes: ['user-4', 'user-19'],
    src: '/user-18.jpg',
  },
  {
    id: 'card-19',
    userId: 'user-19',
    teachSkill: [{ title: 'Ментальное здоровье', type: 'lifestyle', subType: 'mental-health' }],
    learnSkill: [
      { title: 'Арт-терапия', type: 'art', subType: 'drawing' },
      { title: 'Нейропсихология', type: 'education', subType: 'cognitive-skills' },
    ],
    name: 'Денис',
    city: 'Омск',
    age: 37,
    description: 'Психолог, специализируюсь на когнитивных методиках',
    fullDescription:
      'Научу техникам управления стрессом и тревожностью. Расскажу как развивать эмоциональный интеллект. Поделюсь упражнениями для улучшения концентрации. Научу методам самодиагностики психического состояния. Расскажу как выстраивать здоровые границы в отношениях.',
    gender: 'male',
    createdAt: 1674086400000,
    likes: ['user-7', 'user-18'],
    src: '/user-19.jpg',
  },
  {
    id: 'card-20',
    userId: 'user-20',
    teachSkill: [{ title: 'Испанский язык', type: 'languages', subType: 'spanish' }],
    learnSkill: [
      { title: 'Фламенко', type: 'art', subType: 'other' },
      { title: 'Латиноамериканская кухня', type: 'home', subType: 'cooking' },
    ],
    name: 'Анастасия',
    city: 'Ростов-на-Дону',
    age: 28,
    description: 'Преподаватель испанского, люблю латиноамериканскую культуру',
    fullDescription:
      'Научу свободно общаться на бытовые темы на испанском. Расскажу особенности произношения в разных странах. Поделюсь техниками быстрого расширения словарного запаса. Научу понимать испанские песни и фильмы. Расскажу о культурных особенностях испаноязычных стран.',
    gender: 'female',
    createdAt: 1674172800000,
    likes: ['user-5', 'user-15'],
    src: '/user-20.jpg',
  },

  // 21-30
  {
    id: 'card-21',
    userId: 'user-21',
    teachSkill: [{ title: 'Китайский язык', type: 'languages', subType: 'chinese' }],
    learnSkill: [
      { title: 'Китайская каллиграфия', type: 'art', subType: 'drawing' },
      { title: 'Тайцзицюань', type: 'lifestyle', subType: 'yoga' },
    ],
    name: 'Георгий',
    city: 'Москва',
    age: 33,
    description: 'Синолог, изучаю традиционные китайские практики',
    fullDescription:
      'Научу основам китайского языка и тонам. Расскажу как запоминать иероглифы с помощью мнемотехник. Поделюсь техниками правильного произношения. Научу вести простые диалоги. Расскажу о культурных особенностях Китая и деловом этикете.',
    gender: 'male',
    createdAt: 1674259200000,
    likes: ['user-14', 'user-23'],
    src: '/user-21.jpg',
  },
  {
    id: 'card-22',
    userId: 'user-22',
    teachSkill: [{ title: 'Цифровая иллюстрация', type: 'art', subType: 'drawing' }],
    learnSkill: [
      { title: 'Анимация', type: 'art', subType: 'mounting' },
      { title: 'UI/UX дизайн', type: 'business', subType: 'brand' },
    ],
    name: 'Валерия',
    city: 'Санкт-Петербург',
    age: 26,
    description: 'Иллюстратор, работаю в цифровом формате',
    fullDescription:
      'Научу создавать иллюстрации в Procreate и Adobe Illustrator. Расскажу о принципах композиции и цветовых сочетаниях. Поделюсь техниками разработки персонажей. Научу работать с графическими планшетами. Расскажу как создать портфолио и найти первых клиентов.',
    gender: 'female',
    createdAt: 1674345600000,
    likes: ['user-11', 'user-27'],
    src: '/user-22.jpg',
  },
  {
    id: 'card-23',
    userId: 'user-23',
    teachSkill: [{ title: 'Французский язык', type: 'languages', subType: 'french' }],
    learnSkill: [
      { title: 'Французская литература', type: 'education', subType: 'personal-development' },
      { title: 'Виноделие', type: 'lifestyle', subType: 'other' },
    ],
    name: 'Артур',
    city: 'Новосибирск',
    age: 30,
    description: 'Преподаватель французского, увлекаюсь литературой',
    fullDescription:
      'Научу правильному французскому произношению. Расскажу особенности грамматики и спряжения глаголов. Поделюсь техниками понимания на слух. Научу читать французскую литературу в оригинале. Расскажу о культурных особенностях разных регионов Франции.',
    gender: 'male',
    createdAt: 1674432000000,
    likes: ['user-21'],
    src: '/user-23.jpg',
  },
  {
    id: 'card-24',
    userId: 'user-24',
    teachSkill: [
      { title: 'Психология общения', type: 'education', subType: 'personal-development' },
    ],
    learnSkill: [
      { title: 'НЛП-практики', type: 'education', subType: 'cognitive-skills' },
      { title: 'Ораторское мастерство', type: 'business', subType: 'brand' },
    ],
    name: 'Юлия',
    city: 'Екатеринбург',
    age: 35,
    description: 'Психолог, помогаю улучшить коммуникативные навыки',
    fullDescription:
      'Научу техникам активного слушания и эмпатии. Расскажу как располагать к себе людей. Поделюсь секретами невербального общения. Научу выходить из конфликтных ситуаций. Расскажу как выражать мысли четко и убедительно.',
    gender: 'female',
    createdAt: 1674518400000,
    likes: ['user-15', 'user-28'],
    src: '/user-24.jpg',
  },
  {
    id: 'card-25',
    userId: 'user-25',
    teachSkill: [{ title: 'Анализ данных', type: 'education', subType: 'training' }],
    learnSkill: [
      { title: 'Машинное обучение', type: 'education', subType: 'cognitive-skills' },
      { title: 'Деловой английский', type: 'languages', subType: 'english' },
    ],
    name: 'Роман',
    city: 'Казань',
    age: 29,
    description: 'Аналитик данных, развиваюсь в области AI',
    fullDescription:
      'Научу основам работы с Python для анализа данных. Расскажу как визуализировать данные в Tableau. Поделюсь техниками очистки и подготовки данных. Научу строить прогнозные модели. Расскажу как интерпретировать результаты анализа для бизнеса.',
    gender: 'male',
    createdAt: 1674604800000,
    likes: ['user-12', 'user-30'],
    src: '/user-25.jpg',
  },
  {
    id: 'card-26',
    userId: 'user-26',
    teachSkill: [{ title: 'Здоровое питание', type: 'lifestyle', subType: 'nutrition' }],
    learnSkill: [
      { title: 'Фитнес-тренировки', type: 'lifestyle', subType: 'yoga' },
      { title: 'Приготовление смузи', type: 'home', subType: 'cooking' },
    ],
    name: 'Евгения',
    city: 'Нижний Новгород',
    age: 31,
    description: 'Нутрициолог, помогаю сбалансировать рацион',
    fullDescription:
      'Научу составлять сбалансированный рацион под ваши цели. Расскажу как считать КБЖУ без стресса. Поделюсь рецептами полезных и вкусных блюд. Научу разбираться в составе продуктов. Расскажу как поддерживать режим питания в путешествиях.',
    gender: 'female',
    createdAt: 1674691200000,
    likes: ['user-17', 'user-29'],
    src: '/user-26.jpg',
  },
  {
    id: 'card-27',
    userId: 'user-27',
    teachSkill: [{ title: 'Видеоблогинг', type: 'art', subType: 'mounting' }],
    learnSkill: [
      { title: 'Операторское мастерство', type: 'art', subType: 'photo' },
      { title: 'Продвижение в YouTube', type: 'business', subType: 'marketing' },
    ],
    name: 'Максим',
    city: 'Челябинск',
    age: 24,
    description: 'Видеоблогер, создаю образовательный контент',
    fullDescription:
      'Научу создавать качественный видеоконтент с нуля. Расскажу как писать сценарии для роликов. Поделюсь техниками съемки на смартфон. Научу базовому монтажу в мобильных приложениях. Расскажу как продвигать канал и набирать аудиторию.',
    gender: 'male',
    createdAt: 1674777600000,
    likes: ['user-22', 'user-18'],
    src: '/user-27.jpg',
  },
  {
    id: 'card-28',
    userId: 'user-28',
    teachSkill: [{ title: 'Английский для IT', type: 'languages', subType: 'english' }],
    learnSkill: [
      { title: 'Техническое письмо', type: 'education', subType: 'training' },
      { title: 'Основы программирования', type: 'education', subType: 'cognitive-skills' },
    ],
    name: 'Арина',
    city: 'Самара',
    age: 27,
    description: 'Преподаватель английского для технических специалистов',
    fullDescription:
      'Научу техническому английскому для разработчиков. Расскажу как читать документацию и Stack Overflow. Поделюсь лексикой для собеседований в IT-компаниях. Научу писать профессиональные emails. Расскажу как участвовать в конференциях и митапах.',
    gender: 'female',
    createdAt: 1674864000000,
    likes: ['user-24', 'user-5'],
    src: '/user-28.jpg',
  },
  {
    id: 'card-29',
    userId: 'user-29',
    teachSkill: [{ title: 'Арт-терапия', type: 'art', subType: 'drawing' }],
    learnSkill: [
      { title: 'Детская психология', type: 'education', subType: 'personal-development' },
      { title: 'Сказкотерапия', type: 'education', subType: 'other' },
    ],
    name: 'Вероника',
    city: 'Омск',
    age: 32,
    description: 'Арт-терапевт, работаю с детьми и взрослыми',
    fullDescription:
      'Научу техникам арт-терапии для снятия стресса. Расскажу как анализировать рисунки. Поделюсь упражнениями для развития креативности. Научу проводить сессии с детьми. Расскажу как использовать искусство для самопознания.',
    gender: 'female',
    createdAt: 1674950400000,
    likes: ['user-19', 'user-26'],
    src: '/user-29.jpg',
  },
  {
    id: 'card-30',
    userId: 'user-30',
    teachSkill: [{ title: 'Финансовая грамотность', type: 'home', subType: 'home-finances' }],
    learnSkill: [
      { title: 'Инвестиции', type: 'home', subType: 'home-finances' },
      { title: 'Экономическая психология', type: 'education', subType: 'cognitive-skills' },
    ],
    name: 'Константин',
    city: 'Ростов-на-Дону',
    age: 39,
    description: 'Финансовый консультант, помогаю с инвестициями',
    fullDescription:
      'Научу основам финансового планирования. Расскажу как создать резервный фонд. Поделюсь стратегиями накопления. Научу оценивать риски инвестиций. Расскажу как защитить капитал от инфляции.',
    gender: 'male',
    createdAt: 1675036800000,
    likes: ['user-13', 'user-25'],
    src: '/user-30.jpg',
  },

  // 31-40
  {
    id: 'card-31',
    userId: 'user-31',
    teachSkill: [{ title: 'Скорочтение', type: 'education', subType: 'training' }],
    learnSkill: [
      { title: 'Мнемотехники', type: 'education', subType: 'cognitive-skills' },
      { title: 'Конспектирование', type: 'education', subType: 'personal-development' },
    ],
    name: 'Татьяна',
    city: 'Москва',
    age: 28,
    description: 'Тренер по развитию памяти и скорочтению',
    fullDescription:
      'Научу читать в 2-3 раза быстрее без потери понимания. Расскажу как увеличить поле зрения при чтении. Поделюсь техниками подавления субвокализации. Научу запоминать прочитанное надолго. Расскажу как применять скорочтение для работы и учебы.',
    gender: 'female',
    createdAt: 1675123200000,
    likes: ['user-21', 'user-33'],
    src: '/user-31.jpg',
  },
  {
    id: 'card-32',
    userId: 'user-32',
    teachSkill: [{ title: 'Создание презентаций', type: 'business', subType: 'brand' }],
    learnSkill: [
      { title: 'Сторителлинг', type: 'business', subType: 'marketing' },
      { title: 'Дизайн слайдов', type: 'art', subType: 'drawing' },
    ],
    name: 'Игорь',
    city: 'Санкт-Петербург',
    age: 34,
    description: 'Специалист по визуальным коммуникациям',
    fullDescription:
      'Научу создавать эффектные презентации в PowerPoint и Keynote. Расскажу принципы визуального сторителлинга. Поделюсь техниками структурирования информации. Научу работать с инфографикой. Расскажу как удерживать внимание аудитории.',
    gender: 'male',
    createdAt: 1675209600000,
    likes: ['user-12', 'user-22'],
    src: '/user-32.jpg',
  },
  {
    id: 'card-33',
    userId: 'user-33',
    teachSkill: [{ title: 'Немецкий для начинающих', type: 'languages', subType: 'german' }],
    learnSkill: [
      { title: 'История Германии', type: 'education', subType: 'personal-development' },
      { title: 'Деловая переписка', type: 'business', subType: 'sales' },
    ],
    name: 'Людмила',
    city: 'Новосибирск',
    age: 41,
    description: 'Преподаватель немецкого с историческим образованием',
    fullDescription:
      'Научу основам немецкой грамматики и лексики. Расскажу как правильно произносить сложные звуки. Поделюсь техниками запоминания артиклей. Научу вести простые диалоги. Расскажу о культурных особенностях немецкоязычных стран.',
    gender: 'female',
    createdAt: 1675296000000,
    likes: ['user-31', 'user-35'],
    src: '/user-33.jpg',
  },
  {
    id: 'card-34',
    userId: 'user-34',
    teachSkill: [{ title: 'Основы живописи', type: 'art', subType: 'drawing' }],
    learnSkill: [
      { title: 'История искусства', type: 'education', subType: 'personal-development' },
      { title: 'Керамика', type: 'art', subType: 'other' },
    ],
    name: 'Вадим',
    city: 'Екатеринбург',
    age: 30,
    description: 'Художник, преподаю основы академического рисунка',
    fullDescription:
      'Научу основам композиции и перспективы. Расскажу как работать с разными материалами. Поделюсь техниками смешивания цветов. Научу видеть пропорции и объем. Расскажу как развить художественное видение.',
    gender: 'male',
    createdAt: 1675382400000,
    likes: ['user-24', 'user-36'],
    src: '/user-34.jpg',
  },
  {
    id: 'card-35',
    userId: 'user-35',
    teachSkill: [{ title: 'Тайм-менеджмент', type: 'education', subType: 'personal-development' }],
    learnSkill: [
      { title: 'Продуктивность', type: 'education', subType: 'training' },
      { title: 'Управление стрессом', type: 'lifestyle', subType: 'mental-health' },
    ],
    name: 'Ангелина',
    city: 'Казань',
    age: 29,
    description: 'Коуч по продуктивности и управлению временем',
    fullDescription:
      'Научу эффективно планировать день и неделю. Расскажу как расставлять приоритеты. Поделюсь техниками борьбы с прокрастинацией. Научу делегировать задачи. Расскажу как сохранять баланс между работой и отдыхом.',
    gender: 'female',
    createdAt: 1675468800000,
    likes: ['user-33', 'user-38'],
    src: '/user-35.jpg',
  },
  {
    id: 'card-36',
    userId: 'user-36',
    teachSkill: [{ title: 'Функциональный тренинг', type: 'lifestyle', subType: 'yoga' }],
    learnSkill: [
      { title: 'Спортивная диетология', type: 'lifestyle', subType: 'nutrition' },
      { title: 'Анатомия движения', type: 'education', subType: 'training' },
    ],
    name: 'Станислав',
    city: 'Нижний Новгород',
    age: 32,
    description: 'Фитнес-тренер, специализируюсь на функциональных тренировках',
    fullDescription:
      'Научу правильной технике выполнения упражнений. Расскажу как составить программу тренировок. Поделюсь техниками работы с собственным весом. Научу предотвращать травмы. Расскажу как мотивировать себя на регулярные занятия.',
    gender: 'male',
    createdAt: 1675555200000,
    likes: ['user-34', 'user-40'],
    src: '/user-36.jpg',
  },
  {
    id: 'card-37',
    userId: 'user-37',
    teachSkill: [{ title: 'Основы саунд-дизайна', type: 'art', subType: 'music' }],
    learnSkill: [
      { title: 'Запись вокала', type: 'art', subType: 'music' },
      { title: 'Сведение треков', type: 'art', subType: 'mounting' },
    ],
    name: 'Александра',
    city: 'Челябинск',
    age: 26,
    description: 'Саунд-дизайнер, работаю с электронной музыкой',
    fullDescription:
      'Научу основам работы в Ableton Live. Расскажу как создавать звуковые эффекты. Поделюсь техниками сэмплирования. Научу обрабатывать вокал. Расскажу как создавать атмосферные звуковые ландшафты.',
    gender: 'female',
    createdAt: 1675641600000,
    likes: ['user-27', 'user-39'],
    src: '/user-37.jpg',
  },
  {
    id: 'card-38',
    userId: 'user-38',
    teachSkill: [{ title: 'Основы астрологии', type: 'lifestyle', subType: 'mindfulness' }],
    learnSkill: [
      { title: 'Нумерология', type: 'lifestyle', subType: 'other' },
      { title: 'Психология личности', type: 'education', subType: 'personal-development' },
    ],
    name: 'Борис',
    city: 'Самара',
    age: 45,
    description: 'Астролог, изучаю взаимосвязь звезд и характера',
    fullDescription:
      'Научу основам натальной астрологии. Расскажу как составлять космограмму. Поделюсь техниками интерпретации аспектов. Научу работать с астрологическими домами. Расскажу как применять астрологию для самопознания.',
    gender: 'male',
    createdAt: 1675728000000,
    likes: ['user-35'],
    src: '/user-38.jpg',
  },
  {
    id: 'card-39',
    userId: 'user-39',
    teachSkill: [{ title: 'Французская выпечка', type: 'home', subType: 'cooking' }],
    learnSkill: [
      { title: 'Декорирование тортов', type: 'art', subType: 'drawing' },
      { title: 'Фуд-стайлинг', type: 'art', subType: 'photo' },
    ],
    name: 'Элина',
    city: 'Омск',
    age: 31,
    description: 'Кондитер, специализируюсь на французских десертах',
    fullDescription:
      'Научу готовить воздушные круассаны с идеальной слоистостью. Покажу секреты приготовления нежного тарт Татен с карамелизированными яблоками. Расскажу, как работать с миндальным тестом для изысканных пирожных. Научу создавать стабильные муссы и крем-чибоу. Поделюсь профессиональными техниками работы с кондитерским мешком и насадками.',
    gender: 'female',
    createdAt: 1675814400000,
    likes: ['user-37', 'user-20'],
    src: '/user-39.jpg',
  },
  {
    id: 'card-40',
    userId: 'user-40',
    teachSkill: [{ title: 'Основы предпринимательства', type: 'business', subType: 'sales' }],
    learnSkill: [
      { title: 'Управление рисками', type: 'business', subType: 'team-management' },
      { title: 'Юридические аспекты бизнеса', type: 'education', subType: 'training' },
    ],
    name: 'Глеб',
    city: 'Ростов-на-Дону',
    age: 36,
    description: 'Предприниматель, делюсь опытом ведения бизнеса',
    fullDescription:
      'Научу составлять бизнес-план и считать unit-экономику. Расскажу, как выбрать прибыльную нишу и проанализировать конкурентов. Поделюсь техниками привлечения первых клиентов без бюджета. Научу формировать ценностное предложение и УТП. Расскажу, как избежать типичных ошибок начинающих предпринимателей и выстроить устойчивую бизнес-модель.',
    gender: 'male',
    createdAt: 1675900800000,
    likes: ['user-36', 'user-25'],
    src: '/user-40.jpg',
  },
];
